name: Android CI

on:
  push:
    branches: [ master ]
    
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
  pull_request:
    branches: 
      # Push events on main branch
      - master
      # Push events to branches matching refs/heads/feature/octocat
      - 'feature/**'
      # Push events to branches matching refs/heads/releases/10
      - 'releases/**'
      
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
